### PR TITLE
Peep through image desc modifications during waterfall generation.

### PR DESCRIPTION
**Pull request by perlfu**
An issue was introduced with PR #1827, where waterfall tracing
interacted incorrectly with workaround code that modifies image
descriptors on some GFX10.3 ASICs.
This would result in compilation errors for some shaders.

This patches fixes the issue in two ways:
 * The scalarizer code now correctly updates the non-uniform
   instruction with waterfall replacement values.
 * The tracing code can now peep through workarounds like those
   used on gfx1032, meaning waterfalls output should be identical
   on these ASICs.

### CODE REVIEW

File: lgc/builder/BuilderImpl.cpp [hunk 1]
```diff
@@ -348,8 +348,36 @@ BranchInst *BuilderImplBase::createIf(Value *condition, bool wantElse, const Twi
...
+      for (Value *operand : updatedElement->operands()) {
+        if (auto extract = dyn_cast<ExtractElementInst>(operand)) {
+          // Only dynamic value must be ExtractElementInst based on load.
+          if (dyn_cast<LoadInst>(extract->getOperand(0)) != load)
+            return nonUniformVal;
+        } else if (!dyn_cast<Constant>(operand)) {
+          return nonUniformVal;
+        }
+      }
+    } else if (!dyn_cast<Constant>(insert->getOperand(1))) {
```
Comment (nhaehnle) [inline lgc/builder/BuilderImpl.cpp:377]: Use `isa<Constant>`

**Review by nhaehnle — COMMENTED** [review]
I'm unhappy that this is so specific to a specific pattern and therefore fragile. On the other hand, getting a proper solid foundation for waterfall loops would really require something like regions (explicit nesting) which we can't reasonably represent in LLVM IR, so... I suppose this is okay?

(Hmm, maybe we could have a `callbr`-based representation of waterfall loops?)

**Comment by perlfu** [comment]
> I'm unhappy that this is so specific to a specific pattern and therefore fragile. On the other hand, getting a proper solid foundation for waterfall loops would really require something like regions (explicit nesting) which we can't reasonably represent in LLVM IR, so... I suppose this is okay?
> 
> (Hmm, maybe we could have a `callbr`-based representation of waterfall loops?)

Reasonable concerns.
Technical the waterfall loops work even if the fragile pattern is broken, just they are less efficient.

One of the things that irritated me working on this patch is that the waterfall loop insertion works on the IR during the LGC replay pass.
So there is no direct way to test the waterfall transformation as it happens on IR that is "still being formed".
Ideally it would be a separate pass, working on some kind of LGC markers after replay.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3f9020836301795e5f5f99003b5ea3dc1aab757e
<details><summary>CTS tests (Failed: 0/220357)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73361 (51.1%)</li>
<li>Failed: 0/73361 (0.0%)</li>
<li>Not Supported: 35867/73361 (48.9%)</li><li>Warnings: 0/73361 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks for the update.

> One of the things that irritated me working on this patch is that the waterfall loop insertion works on the IR during the LGC replay pass.
> So there is no direct way to test the waterfall transformation as it happens on IR that is "still being formed".
> Ideally it would be a separate pass, working on some kind of LGC markers after replay.

Yeah. This is the kind of thing that I hope we can improve more systematically based on the dialects work.

In the meantime, I think it's okay to use this change.
