### ISSUE TITLE
Build failure with -Werror after #1201

### ISSUE THREAD

**Issue by dnovillo** [GPUOpen-Drivers/llpc#1213]
Our builds are configured with `-Werror`.  They are now failing with

```
llpc/llpc/translator/lib/SPIRV/SPIRVToLLVMDbgTran.cpp:907:16: error: using the result of an assignment as a condition without parentheses [-Werror,-Wparentheses]
  if (LineInfo = SpirvInst->getLine()) {
      ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```

If think the assignment inside the `if()` is intended, given the rest of the logic.  Should this also add `!= nullptr`?

**Comment by nhaehnle** [comment]
This is outdated.
